# Generated by Django 5.0.8 on 2024-10-02 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_cat', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Essencia',
            fields=[
                ('id_essencia', models.AutoField(primary_key=True, serialize=False)),
                ('essencia', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant_velas', models.IntegerField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id_tamanho', models.AutoField(primary_key=True, serialize=False)),
                ('tamanho', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('descrição', models.TextField(blank=True, max_length=50, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='velas/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='velas.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id_variante', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('essencia_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='velas.essencia')),
                ('produto_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='velas.produto')),
                ('tamaho_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='velas.tamanho')),
            ],
        ),
    ]
