# Generated by Django 5.0.8 on 2025-01-30 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_cat', models.AutoField(primary_key=True, serialize=False)),
                ('nome_categoria', models.CharField(default='nome_categoria', max_length=25)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cli', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Número', models.CharField(max_length=11)),
                ('Mensagem', models.TextField(default='', max_length=1000)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Essencia',
            fields=[
                ('id_essencia', models.AutoField(primary_key=True, serialize=False)),
                ('nome_essencia', models.CharField(default='nome essencia', max_length=25)),
            ],
            options={
                'verbose_name': 'Essência',
                'verbose_name_plural': 'Essências',
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant_velas', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Estoque',
                'verbose_name_plural': 'Estoques',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id_tamanho', models.AutoField(primary_key=True, serialize=False)),
                ('nome_tamanho', models.CharField(blank=True, max_length=25, null=True)),
                ('peso', models.CharField(blank=True, null=True)),
                ('altura', models.FloatField(default=5.0)),
                ('diâmetro', models.FloatField(default=3.0)),
                ('circunferência', models.FloatField(default=3.0)),
            ],
            options={
                'verbose_name': 'Tamanho',
                'verbose_name_plural': 'Tamanhos',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descricao', models.TextField(blank=True, max_length=200, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='velas/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vela_categoria', to='velas.categoria')),
                ('essencia', models.ManyToManyField(to='velas.essencia')),
                ('tamanhos', models.ForeignKey(default='tamanho', on_delete=django.db.models.deletion.PROTECT, related_name='produto', to='velas.tamanho')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Destaques',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('destaque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prod_destaque', to='velas.produto')),
            ],
        ),
    ]
