# Generated by Django 5.0.8 on 2024-10-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='quant_velas',
            field=models.IntegerField(),
        ),
    ]
