# Generated by Django 5.0.8 on 2024-10-03 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velas', '0002_alter_estoque_quant_velas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='descrição',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='variante',
            old_name='essencia_id',
            new_name='essencia',
        ),
        migrations.RenameField(
            model_name='variante',
            old_name='produto_id',
            new_name='produto',
        ),
        migrations.RenameField(
            model_name='variante',
            old_name='tamaho_id',
            new_name='tamanho',
        ),
    ]
