# Generated by Django 5.0.8 on 2024-10-08 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velas', '0003_rename_descrição_produto_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='variante',
            name='essencia',
        ),
        migrations.DeleteModel(
            name='Estoque',
        ),
        migrations.RemoveField(
            model_name='variante',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='variante',
            name='tamanho',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Essencia',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Tamanho',
        ),
        migrations.DeleteModel(
            name='Variante',
        ),
    ]
