# Generated by Django 5.0.8 on 2024-10-25 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velas', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cli', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Número', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Destaques',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('destaque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prod_destaque', to='velas.produto')),
            ],
        ),
    ]
