# Generated by Django 5.0.8 on 2024-10-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velas', '0006_clientes_destaques'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='Mensagem',
            field=models.TextField(default='Mensagem indisponível.', max_length=1000),
        ),
    ]
