# Generated by Django 5.0.8 on 2024-10-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velas', '0007_clientes_mensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='Mensagem',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
