# Generated by Django 5.0.8 on 2024-11-03 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velas', '0008_alter_clientes_mensagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='categoria',
            new_name='nome_categoria',
        ),
    ]
