# Generated by Django 5.0.8 on 2024-12-07 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velas', '0009_rename_categoria_categoria_nome_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tamanho',
            old_name='tamanho',
            new_name='nome_tamanho',
        ),
    ]
