# Generated by Django 5.0.8 on 2024-12-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velas', '0010_rename_tamanho_tamanho_nome_tamanho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='tamanho',
        ),
        migrations.AddField(
            model_name='produto',
            name='tamanhos',
            field=models.ManyToManyField(related_name='produto', to='velas.tamanho'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
