# Generated by Django 5.0.8 on 2024-12-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velas', '0011_remove_produto_tamanho_produto_tamanhos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tamanhos',
            field=models.ManyToManyField(related_name='tamanho', to='velas.tamanho'),
        ),
    ]
