# Generated by Django 5.0.8 on 2024-12-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velas', '0013_alter_produto_tamanhos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tamanho',
            name='altura',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='tamanho',
            name='comprimento',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='tamanho',
            name='largura',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='tamanho',
            name='peso',
            field=models.FloatField(default=2.0),
        ),
    ]
