# Generated by Django 5.0.8 on 2024-12-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velas', '0013_alter_produto_tamanhos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tamanho',
            name='altura',
            field=models.FloatField(default='altura padrao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tamanho',
            name='comprimento',
            field=models.FloatField(default='comprimento padrao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tamanho',
            name='largura',
            field=models.FloatField(default='largura padrao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tamanho',
            name='peso',
            field=models.FloatField(default='peso padrao'),
            preserve_default=False,
        ),
    ]
