# Generated by Django 5.0.8 on 2024-12-27 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velas', '0014_tamanho_altura_tamanho_comprimento_tamanho_largura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tamanho',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='tamanho',
            name='comprimento',
        ),
        migrations.RemoveField(
            model_name='tamanho',
            name='largura',
        ),
        migrations.RemoveField(
            model_name='tamanho',
            name='peso',
        ),
    ]
