# Generated by Django 5.0.8 on 2025-01-02 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velas', '0014_tamanho_altura_tamanho_comprimento_tamanho_largura_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tamanho',
            old_name='comprimento',
            new_name='circunferência',
        ),
        migrations.RenameField(
            model_name='tamanho',
            old_name='largura',
            new_name='diâmetro',
        ),
    ]
