# Generated by Django 5.0.8 on 2025-01-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velas', '0015_rename_comprimento_tamanho_circunferência_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamanho',
            name='peso',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
