# Generated by Django 5.0.8 on 2024-12-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velas', '0015_remove_tamanho_altura_remove_tamanho_comprimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tamanho',
            name='altura',
            field=models.CharField(default='altura padrao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tamanho',
            name='comprimento',
            field=models.CharField(default='comprimento padrao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tamanho',
            name='largura',
            field=models.CharField(default='largura padrao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tamanho',
            name='peso',
            field=models.CharField(default='peso padrao'),
            preserve_default=False,
        ),
    ]
