# Generated by Django 5.0.8 on 2025-01-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velas', '0016_alter_tamanho_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamanho',
            name='peso',
            field=models.CharField(blank=True, null=True),
        ),
    ]
