# Generated by Django 5.0.8 on 2024-12-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velas', '0016_tamanho_altura_tamanho_comprimento_tamanho_largura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamanho',
            name='altura',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tamanho',
            name='comprimento',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tamanho',
            name='largura',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tamanho',
            name='peso',
            field=models.CharField(blank=True, null=True),
        ),
    ]
