# Generated by Django 5.0.8 on 2024-12-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velas', '0020_tamanho_altura_tamanho_comprimento_tamanho_largura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamanho',
            name='altura',
            field=models.FloatField(blank=True, default=15.0, null=True),
        ),
        migrations.AlterField(
            model_name='tamanho',
            name='comprimento',
            field=models.FloatField(blank=True, default=3.0, null=True),
        ),
        migrations.AlterField(
            model_name='tamanho',
            name='largura',
            field=models.FloatField(blank=True, default=2.0, null=True),
        ),
        migrations.AlterField(
            model_name='tamanho',
            name='peso',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
    ]
