# Generated by Django 5.0.8 on 2024-12-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velas', '0021_alter_tamanho_altura_alter_tamanho_comprimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamanho',
            name='altura',
            field=models.FloatField(default=15.0),
        ),
        migrations.AlterField(
            model_name='tamanho',
            name='comprimento',
            field=models.FloatField(default=3.0),
        ),
        migrations.AlterField(
            model_name='tamanho',
            name='largura',
            field=models.FloatField(default=2.0),
        ),
        migrations.AlterField(
            model_name='tamanho',
            name='peso',
            field=models.FloatField(default=1.0),
        ),
    ]
