# Generated by Django 5.0.8 on 2025-01-07 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velas', '0017_alter_tamanho_peso'),
        ('velas', '0026_alter_tamanho_altura_alter_tamanho_comprimento_and_more'),
    ]

    operations = [
    ]
