# Generated by Django 5.0.8 on 2025-01-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velas', '0027_merge_20250106_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamanho',
            name='altura',
            field=models.FloatField(default=5.0),
        ),
        migrations.AlterField(
            model_name='tamanho',
            name='circunferência',
            field=models.FloatField(default=3.0),
        ),
        migrations.AlterField(
            model_name='tamanho',
            name='diâmetro',
            field=models.FloatField(default=3.0),
        ),
    ]
