# Generated by Django 5.0.8 on 2025-01-07 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velas', '0028_alter_tamanho_altura_alter_tamanho_circunferência_and_more'),
    ]

    operations = [
    ]
