# Generated by Django 5.0.8 on 2025-01-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velas', '0030_remove_produto_tamanhos_produto_tamanhos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essencia',
            old_name='essencia',
            new_name='nome_essencia',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='essencia',
        ),
        migrations.AddField(
            model_name='produto',
            name='essencia',
            field=models.ManyToManyField(related_name='vela_esencia', to='velas.essencia'),
        ),
    ]
