# Generated by Django 5.0.8 on 2025-01-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velas', '0031_rename_essencia_essencia_nome_essencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='essencia',
            field=models.ManyToManyField(to='velas.essencia'),
        ),
    ]
